Tests fixes and small adjustments
isar-community/isar pull request #34
Opened 2024-03-23 03:55 UTC by vicenterusso

2024-03-23 09:11 UTC, mrclauss commented on packages/isar/pubspec.yaml
> +  isar_test:
Do you need this extra dependency (for everybody using Isar)?

2024-03-23 09:12 UTC, mrclauss commented on packages/isar_flutter_libs/pubspec.yaml
> +  isar:
Referring local paths won't work for everybody else

2024-03-23 09:13 UTC, mrclauss requested changes
Referring to local paths in pubspec works for your (or the github action) setup, but not for the end user...

2024-03-23 14:56 UTC, vicenterusso commented
Do you have a use case where this will not work for end users?

2024-03-23 15:07 UTC, mrclauss commented
> Do you have a use case where this will not work for end users?

Uhm for everyone :)
I'm pretty sure you cannot publish a package to pub.dev or our package repo that refers to local paths in its dependencies...

2024-03-23 15:47 UTC, vicenterusso commented
> > Do you have a use case where this will not work for end users?
> 
> Uhm for everyone :) I'm pretty sure you cannot publish a package to pub.dev or our package repo that refers to local paths in its dependencies... This will only work if you have the isar sources checked out locally (which the regular user won't want)

Should be an easy change after publishing then

2024-03-26 08:20 UTC, richard457 commented
we might need to consider https://melos.invertase.dev/ for local packages this can help when it is time to publish as well to pub.dev

2024-03-27 16:52 UTC, mrclauss approved these changes

2024-03-27 16:52 UTC, mrclauss commented
Looks good to me

2024-03-27 17:25 UTC, merged