sets to loose js version
isar-community/isar pull request #61
Opened 2024-04-24 13:33 UTC by vicenterusso

We can safely set to `any` as web bindings are not available to v3

Fixes #16

2024-04-24 16:17 UTC, mrclauss requested changes
Do we need JS at all?

2024-04-24 16:17 UTC, mrclauss commented on packages/isar/pubspec.yaml
> +  js: any
Question is: Why do we need the dependency at all?

2024-04-24 19:50 UTC, vicenterusso commented on packages/isar/pubspec.yaml
> +  js: any
We dont, but I believe that removing it could lead to compile errors, so maybe its easier to just let it be than trying to fix by removing it. At least for now

2024-04-24 19:52 UTC, mrclauss commented on packages/isar/pubspec.yaml
> +  js: any
Ok

2024-04-24 19:52 UTC, mrclauss approved these changes

2024-04-24 21:03 UTC, merged

2024-05-01 18:24 UTC, AristideVB commented
Hello @vicenterusso @mrclauss  thank you so much for this update 

How can I access the version including this update in my project 

If I import Isar as suggested in the documentation it does not include your update 😕

```yaml
isar_version: &isar_version 3.1.3 # define the version to be used

dependencies:
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  build_runner: any
```

this brings another question is : would it be possible to publish this community fork on pub.dev to simplify updates ? 🙏

2024-05-03 15:28 UTC, vicenterusso commented
> would it be possible to publish this community fork on pub.dev to simplify updates ? 🙏

Yes we have plans to publish fork to pub.dev soon... keeping both `isar/isar` and `isar-community/isar` updated and in sync